### ISSUE TITLE
[github-actions] buildx-codelab_otsim build failing

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#6632]
Build started breaking after merging #6454 

```
#9 63.62 ../../src/posix/platform/libopenthread-posix.a(libopenthread_posix_a-system.o): In function `otSysInit':
#9 63.62 /root/src/openthread/src/posix/../../src/posix/platform/system.cpp:116: undefined reference to `__cxa_guard_acquire'
#9 63.62 /root/src/openthread/src/posix/../../src/posix/platform/system.cpp:116: undefined reference to `__cxa_guard_release'
#9 63.62 collect2: error: ld returned 1 exit status
```

[logs_77027.zip](https://github.com/openthread/openthread/files/6481235/logs_77027.zip)

**Comment by bukepo** [comment]
It seems the check only runs over the current main branch code.
