### ISSUE TITLE
EFR32 build failed

### ISSUE THREAD

**Issue by balaji-reddy** [openthread/openthread#2955]
**Describe the bug**
Not able to compile OpenThread for EFR32 target.

**To Reproduce**
Information to reproduce the behavior, including:
1. Build `master` branch using `efr32` makefile for board `BRD4161A`, like
    `make -f examples/Makefile-efr32 BOARD=BRD4161A`

**Expected behavior**
It should compile at least without any blocking errors.

**Console/log output**

```
 /ws/open-source/OpenThread/src/openthread-efr32/examples/../examples/platforms/efr32/radio.c:46:34: fatal error: em_openthread-system.h: No such file or directory
  #include "em_openthread-system.h"
                                   ^
compilation terminated.
make[5]: *** [libopenthread_efr32_a-radio.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [all-recursive] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [do-build-cortex-m4] Error 2
```

**Additional context**
I think it's incorrect header file, it supposed to be **`#include "em_system.h"`**.

**Comment by jwhui** [comment]
Thanks for raising this issue! This bug was introduced with #2927. I’ll submit a fix soon.
