### PR TITLE
[posix] avoid static local variable

### LINKED ISSUE #6632: [github-actions] buildx-codelab_otsim build failing
Build started breaking after merging #6454 

```
#9 63.62 ../../src/posix/platform/libopenthread-posix.a(libopenthread_posix_a-system.o): In function `otSysInit':
#9 63.62 /root/src/openthread/src/posix/../../src/posix/platform/system.cpp:116: undefined reference to `__cxa_guard_acquire'
#9 63.62 /root/src/openthread/src/posix/../../src/posix/platform/system.cpp:116: undefined reference to `__cxa_guard_release'
#9 63.62 collect2: error: ld returned 1 exit status
```

[logs_77027.zip](https://github.com/openthread/openthread/files/6481235/logs_77027.zip)

### PR DESCRIPTION
**Pull request by bukepo**
This commit avoid static local variable so that it will not fail to
build on multi-threading environment.

Fixes #6632.

### CODE REVIEW

**Comment by bukepo** [comment]
There are two commits. One fixes the docker build to use the correct commit, and the other removes static local variable.

**Review by Irving-cl — APPROVED** [review]
LGTM 👍

**Review by jwhui — APPROVED** [review]
