### PR TITLE
[routing-manager] fix call to `StartRoutingPolicyEvaluationJitter()`

### PR DESCRIPTION
**Pull request by jwhui**
Fixes issue introduced with merging #7982 
```
../../third_party/openthread/repo/src/core/border_router/routing_manager.cpp:261:44: error: 'kRoutingPolicyEvaluationJitter' was not declared in this scope
         StartRoutingPolicyEvaluationJitter(kRoutingPolicyEvaluationJitter);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

### CODE REVIEW

**Review by abtink — APPROVED** [review]
Thanks 👍

**Comment by simonlingoogle** [comment]
Thanks
