### PR TITLE
[cc26xx] remove -pedantic-errors from cc26xx driverlib build

### LINKED ISSUE #2362: [CC265x example][Building error]error: initializer element is not a constant expression [-Wpedantic]
Hi,

After changes introduced in #2361 the build process went further for this example but I'm still getting some errors. 

`In file included from /home/aron/devel/openthread/examples/../examples/platforms/cc2650/cc2650_ccfg.c:48:0:
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:389:42: error: initializer element is not a constant expression [-Wpedantic]
 #define DEFAULT_CCFG_MODE_CONF           ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:480:5: note: in expansion of macro 'DEFAULT_CCFG_MODE_CONF'
     DEFAULT_CCFG_MODE_CONF          , // 0x50003FB4
     ^~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:389:42: note: (near initialization for '__ccfg.CCFG_MODE_CONF')
 #define DEFAULT_CCFG_MODE_CONF           ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:480:5: note: in expansion of macro 'DEFAULT_CCFG_MODE_CONF'
     DEFAULT_CCFG_MODE_CONF          , // 0x50003FB4
     ^~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:404:42: error: initializer element is not a constant expression [-Wpedantic]
 #define DEFAULT_CCFG_VOLT_LOAD_0         ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:481:5: note: in expansion of macro 'DEFAULT_CCFG_VOLT_LOAD_0'
     DEFAULT_CCFG_VOLT_LOAD_0        , // 0x50003FB8
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:404:42: note: (near initialization for '__ccfg.CCFG_VOLT_LOAD_0')
 #define DEFAULT_CCFG_VOLT_LOAD_0         ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:481:5: note: in expansion of macro 'DEFAULT_CCFG_VOLT_LOAD_0'
     DEFAULT_CCFG_VOLT_LOAD_0        , // 0x50003FB8
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:410:42: error: initializer element is not a constant expression [-Wpedantic]
 #define DEFAULT_CCFG_VOLT_LOAD_1         ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:482:5: note: in expansion of macro 'DEFAULT_CCFG_VOLT_LOAD_1'
     DEFAULT_CCFG_VOLT_LOAD_1        , // 0x50003FBC
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:410:42: note: (near initialization for '__ccfg.CCFG_VOLT_LOAD_1')
 #define DEFAULT_CCFG_VOLT_LOAD_1         ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:482:5: note: in expansion of macro 'DEFAULT_CCFG_VOLT_LOAD_1'
     DEFAULT_CCFG_VOLT_LOAD_1        , // 0x50003FBC
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:416:42: error: initializer element is not a constant expression [-Wpedantic]
 #define DEFAULT_CCFG_RTC_OFFSET          ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:483:5: note: in expansion of macro 'DEFAULT_CCFG_RTC_OFFSET'
     DEFAULT_CCFG_RTC_OFFSET         , // 0x50003FC0
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:416:42: note: (near initialization for '__ccfg.CCFG_RTC_OFFSET')
 #define DEFAULT_CCFG_RTC_OFFSET          ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:483:5: note: in expansion of macro 'DEFAULT_CCFG_RTC_OFFSET'
     DEFAULT_CCFG_RTC_OFFSET         , // 0x50003FC0
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:421:42: error: initializer element is not a constant expression [-Wpedantic]
 #define DEFAULT_CCFG_FREQ_OFFSET         ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:484:5: note: in expansion of macro 'DEFAULT_CCFG_FREQ_OFFSET'
     DEFAULT_CCFG_FREQ_OFFSET        , // 0x50003FC4
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:421:42: note: (near initialization for '__ccfg.CCFG_FREQ_OFFSET')
 #define DEFAULT_CCFG_FREQ_OFFSET         ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:484:5: note: in expansion of macro 'DEFAULT_CCFG_FREQ_OFFSET'
     DEFAULT_CCFG_FREQ_OFFSET        , // 0x50003FC4
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:431:42: error: initializer element is not a constant expression [-Wpedantic]
 #define DEFAULT_CCFG_BL_CONFIG           ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:489:5: note: in expansion of macro 'DEFAULT_CCFG_BL_CONFIG'
     DEFAULT_CCFG_BL_CONFIG          , // 0x50003FD8
     ^~~~~~~~~~~~~~~~~~~~~~
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:431:42: note: (near initialization for '__ccfg.CCFG_BL_CONFIG')
 #define DEFAULT_CCFG_BL_CONFIG           ( \
                                          ^
/home/aron/devel/openthread/examples/../third_party/ti/devices/cc26x0/startup_files/ccfg.c:489:5: note: in expansion of macro 'DEFAULT_CCFG_BL_CONFIG'
     DEFAULT_CCFG_BL_CONFIG          , // 0x50003FD8
     ^~~~~~~~~~~~~~~~~~~~~~
Makefile:771: recipe for target 'libopenthread_cc2650_a-cc2650_ccfg.o' failed  `

### PR DESCRIPTION
**Pull request by jwhui**
Resolves #2362.

### CODE REVIEW

**Comment by srickardti** [comment]
We noticed these errors when we switched to gcc-arm-none-eabi-6-2017-q1-update. I've brought it up with our driverlib team, and a fixed version will be out with our next SDK. Until then, this will work to avoid the errors.

**Comment by maronows** [comment]
Hi, 
I tried the suggested fix but I also needed to add the same to examples/platforms/cc2650/Makefile.in  to make it work 

`include $(abs_top_nlbuild_autotools_dir)/automake/pre.am

override CFLAGS                              := $(filter-out -pedantic-errors,$(CFLAGS))
override CXXFLAGS                            := $(filter-out -pedantic-errors,$(CXXFLAGS))

include $(abs_top_nlbuild_autotools_dir)/automake/post.am                              `

**Comment by srickardti** [comment]
@maronows when you make a change to a `*.am` file you have to make sure that auto-conf runs again. I do this by re-running the bootstrap script, or using git to clean untracked files.

**Comment by maronows** [comment]
ok, thanks for claryfing.
